### PR TITLE
remove cruft from default Maven settings.xml

### PR DESCRIPTION
**Pull request by Ladicek**
The original `settings.xml` file looks like this:

```xml
<settings>
  <!-- sets the local maven repository outside of the ~/.m2 folder for easier mounting of secrets and repo -->
  <localRepository>${user.home}/.mvnrepository</localRepository>
  <mirrors>
    <mirror>
      <id>nexus</id>
      <mirrorOf>external:*</mirrorOf>
      <url>http://central.maven.org/maven2/</url>
    </mirror>
    <mirror>
      <id>jboss</id>
      <mirrorOf>external:*</mirrorOf>
      <url>https://repository.jboss.org/nexus/content/repositories/thirdparty-releases/</url>
    </mirror>
  </mirrors>

  <!-- lets disable the download progress indicator that fills up logs -->
  <interactiveMode>false</interactiveMode>

  <servers>
    <server>
      <id>local-nexus</id>
      <username>admin</username>
      <password>admin123</password>
    </server>
    <server>
      <id>nexus</id>
      <username>admin</username>
      <password>admin123</password>
    </server>
    <server>
      <id>oss-sonatype-staging</id>
      <username></username>
      <password></password>
    </server>
  </servers>

  <profiles>
    <profile>
      <id>nexus</id>
      <properties>
        <altDeploymentRepository>local-nexus::default::http://content-repository/content/repositories/staging/</altDeploymentRepository>
        <altReleaseDeploymentRepository>local-nexus::default::http://content-repository/content/repositories/staging/</altReleaseDeploymentRepository>
        <altSnapshotDeploymentRepository>local-nexus::default::http://content-repository/content/repositories/snapshots/</altSnapshotDeploymentRepository>
      </properties>
      <repositories>
        <repository>
          <id>central</id>
          <url>http://central</url>
          <releases><enabled>true</enabled></releases>
          <snapshots><enabled>true</enabled></snapshots>
        </repository>
      </repositories>
      <pluginRepositories>
        <pluginRepository>
          <id>central</id>
          <url>http://central</url>
          <releases><enabled>true</enabled></releases>
          <snapshots><enabled>true</enabled></snapshots>
        </pluginRepository>
      </pluginRepositories>
    </profile>
    <profile>
      <id>release</id>
      <properties>
        <gpg.executable>gpg</gpg.executable>
        <gpg.passphrase>mysecretpassphrase</gpg.passphrase>
      </properties>
    </profile>
  </profiles>
  <activeProfiles>
    <!--make the profile active all the time -->
    <activeProfile>nexus</activeProfile>
  </activeProfiles>
</settings>
```

The new value was generated by running

```bash
grep settings.xml jenkins-maven-settings-secret.yml | sed -e 's/  settings.xml: "//' -e 's/"//' | base64 --decode | xmlstarlet edit --delete //mirrors --delete //profile/repositories --delete //profile/pluginRepositories | base64 -w 0
```

So basically, two changes are made:

1. The `<mirrors>` section is removed. This is because it used
   `<mirrorOf>external:*</mirrorOf>`, which basically means that
   no other Maven repository can be used even if the POM defines it.
2. When the `<mirrors>` definition is removed, the repositories
   definitions in the `nexus` profile obviously stop working.
   (They only worked because the URL `http://central` was never
   considered, as it was always overridden by the mirror definition.)
   So the repositories definitions are removed as well.

### CODE REVIEW

**Comment by Ladicek** [comment]
This might have one consequence: previously, the JBoss.org 3rd-party repo was always available. It no longer is. I'd consider that an improvement, because it's closer to how Maven by default works. If the JBoss.org 3rd-party repo should really be always available, I'd do that by adding another profile to the `settings.xml` and defining a repository properly.

**Comment by Ladicek** [comment]
Resolves #119.

**Comment by Ladicek** [comment]
"Waiting for run to start" sounds weird...?

**Comment by rawlingsj** [comment]
Thanks for the PR, we're working on automated e2e tests so we can validate this PR doesn't break anything.  Hopefully we'll get them working soon.

**Comment by Ladicek** [comment]
I've verified that this has been fixed, though not in this repo (which is now deprecated) and I can't find where.

**Pull request closed without merging**
